//! Structures generated by a fractal rule but built from crisp boxes.
//!
//! A kaleidoscopic IFS is a recursive rule: split a block into a grid of
//! cells, keep some of them, maybe twist or lift each child, and repeat inside
//! every kept child. Rather than evaluating that rule as a distance field and
//! meshing it (soft edges, millions of triangles, fidgety collision), the rule
//! is run as a tree and a plain box is placed at every leaf: hard edges by
//! construction, a few triangles per box, and boxes make clean colliders.
//!
//! A [`Style`] is a family; the seed varies each member.

use glam::{Quat, Vec3};

use crate::mesh::ColumnMesh;
use crate::noise::hash01;

/// An oriented box: the leaves (and intermediate nodes) of the tree.
#[derive(Clone, Copy, Debug)]
pub struct Block {
    pub center: Vec3,
    pub rotation: Quat,
    /// Half extents along the block's own axes.
    pub half: Vec3,
    /// How many subdivisions deep this block is.
    pub level: u32,
}

/// Which cells of a block's grid survive into the next level.
#[derive(Clone, Copy, Debug)]
pub enum Keep {
    /// Cells with at most one coordinate away from the grid's boundary: a
    /// Menger-like lattice of edges and corners.
    Lattice,
    /// The cells on the outer columns (x and z on the boundary) plus the top
    /// layer: piers carrying a roof.
    ColumnsAndRoof,
    /// Each cell with this probability.
    Random(f32),
    /// A stepped skyline: each column of cells is kept up to a random height.
    Skyline,
}

/// A family of structures.
#[derive(Clone, Copy, Debug)]
pub struct Style {
    /// Cells per axis (x, y, z) at each split.
    pub divisions: [u32; 3],
    pub keep: Keep,
    /// Maximum subdivision depth.
    pub depth: u32,
    /// Fraction of its cell each child fills; below 1 leaves grooves between
    /// blocks, which is what shows their scale.
    pub gap: f32,
    /// Extra rotation of each child relative to its parent.
    pub twist: Quat,
    /// Chance that a block below the first level stops subdividing early, so
    /// plain masses stand next to finely divided ones.
    pub stop_chance: f32,
    /// Random vertical shift of children, as a fraction of their cell height.
    pub lift: f32,
    /// Blocks smaller than this (half extent, metres) are not split further.
    pub min_half: f32,
    /// Base albedo and its spread.
    pub albedo: f32,
    pub albedo_spread: f32,
}

/// Runs the rule from `root` and returns the leaf blocks, at most `max_blocks`.
pub fn generate(style: &Style, root: Block, seed: u32, max_blocks: usize) -> Vec<Block> {
    let mut leaves = Vec::new();
    split(style, root, seed, 1, max_blocks, &mut leaves);
    leaves
}

fn split(style: &Style, block: Block, seed: u32, path: u32, max_blocks: usize, out: &mut Vec<Block>) {
    let r = |k: i32| hash01(path as i32, k, block.level as i32, seed);
    let leaf = block.level >= style.depth
        || block.half.min_element() < style.min_half
        || (block.level > 0 && r(0) < style.stop_chance)
        || out.len() >= max_blocks;
    if leaf {
        out.push(block);
        return;
    }
    let [nx, ny, nz] = style.divisions;
    // For the skyline: a random kept height per column of cells.
    let column_height = |i: u32, k: u32| {
        let h = hash01(path as i32 * 31 + i as i32, k as i32, block.level as i32 + 7, seed);
        1 + (h * ny as f32) as u32
    };
    let cell = block.half * 2.0 / Vec3::new(nx as f32, ny as f32, nz as f32);
    for k in 0..nz {
        for j in 0..ny {
            for i in 0..nx {
                let inner = |v: u32, n: u32| v > 0 && v + 1 < n;
                let interior = inner(i, nx) as u32 + inner(j, ny) as u32 + inner(k, nz) as u32;
                let child_path = path.wrapping_mul(97).wrapping_add(1 + i + j * 7 + k * 49);
                let rc = |key: i32| hash01(child_path as i32, key, block.level as i32 + 1, seed);
                let keep = match style.keep {
                    Keep::Lattice => interior <= 1,
                    Keep::ColumnsAndRoof => (!inner(i, nx) && !inner(k, nz)) || j + 1 == ny,
                    Keep::Random(p) => rc(1) < p,
                    Keep::Skyline => j < column_height(i, k),
                };
                if !keep {
                    continue;
                }
                let local = Vec3::new(
                    (i as f32 + 0.5) * cell.x - block.half.x,
                    (j as f32 + 0.5) * cell.y - block.half.y + (rc(2) - 0.5) * style.lift * cell.y,
                    (k as f32 + 0.5) * cell.z - block.half.z,
                );
                let child = Block {
                    center: block.center + block.rotation * local,
                    rotation: block.rotation * style.twist,
                    half: cell * 0.5 * style.gap,
                    level: block.level + 1,
                };
                split(style, child, seed, child_path, max_blocks, out);
            }
        }
    }
}

/// Flat-shaded mesh of the blocks. Lower faces and the lower parts of side
/// faces are darker; smaller (deeper) blocks vary more in tone.
pub fn mesh(blocks: &[Block], style: &Style, seed: u32) -> ColumnMesh {
    let mut mesh = ColumnMesh::default();
    const FACES: [([f32; 3], [[f32; 3]; 4]); 6] = [
        ([1., 0., 0.], [[1., -1., -1.], [1., 1., -1.], [1., 1., 1.], [1., -1., 1.]]),
        ([-1., 0., 0.], [[-1., -1., 1.], [-1., 1., 1.], [-1., 1., -1.], [-1., -1., -1.]]),
        ([0., 1., 0.], [[-1., 1., -1.], [-1., 1., 1.], [1., 1., 1.], [1., 1., -1.]]),
        ([0., -1., 0.], [[-1., -1., 1.], [-1., -1., -1.], [1., -1., -1.], [1., -1., 1.]]),
        ([0., 0., 1.], [[-1., -1., 1.], [1., -1., 1.], [1., 1., 1.], [-1., 1., 1.]]),
        ([0., 0., -1.], [[1., -1., -1.], [-1., -1., -1.], [-1., 1., -1.], [1., 1., -1.]]),
    ];
    for (n, b) in blocks.iter().enumerate() {
        let tone = style.albedo
            + style.albedo_spread * (hash01(n as i32, 3, b.level as i32, seed) - 0.5) * 2.0;
        for (normal, corners) in FACES {
            let normal = b.rotation * Vec3::from(normal);
            let base = mesh.positions.len() as u32;
            for c in corners {
                let local = Vec3::from(c);
                let p = b.center + b.rotation * (local * b.half);
                mesh.positions.push(p.to_array());
                mesh.normals.push(normal.to_array());
                mesh.albedo.push(tone);
                // Darker towards the bottom of the block and on its underside.
                let ao = if normal.y < -0.5 { 0.45 } else { 0.75 + 0.25 * (local.y * 0.5 + 0.5) };
                mesh.ao.push(ao);
            }
            mesh.indices.extend_from_slice(&[base, base + 1, base + 2, base, base + 2, base + 3]);
        }
    }
    mesh
}

#[cfg(test)]
mod tests {
    use super::*;

    fn root() -> Block {
        Block { center: Vec3::ZERO, rotation: Quat::IDENTITY, half: Vec3::splat(27.0), level: 0 }
    }

    #[test]
    fn lattice_is_a_menger_sponge() {
        let style = Style {
            divisions: [3, 3, 3],
            keep: Keep::Lattice,
            depth: 3,
            gap: 1.0,
            twist: Quat::IDENTITY,
            stop_chance: 0.0,
            lift: 0.0,
            min_half: 0.0,
            albedo: 0.1,
            albedo_spread: 0.0,
        };
        let blocks = generate(&style, root(), 1, usize::MAX);
        assert_eq!(blocks.len(), 20 * 20 * 20);
        assert!(blocks.iter().all(|b| (b.half - Vec3::ONE).length() < 1e-4));
    }

    #[test]
    fn mesh_faces_point_outwards() {
        let style = Style {
            divisions: [3, 3, 3],
            keep: Keep::Random(0.5),
            depth: 2,
            gap: 0.9,
            twist: Quat::from_rotation_y(0.1),
            stop_chance: 0.2,
            lift: 0.2,
            min_half: 0.5,
            albedo: 0.1,
            albedo_spread: 0.05,
        };
        let blocks = generate(&style, root(), 2, 10_000);
        let m = mesh(&blocks, &style, 2);
        for tri in m.indices.chunks(3) {
            let p = |i: u32| Vec3::from(m.positions[i as usize]);
            let face = (p(tri[1]) - p(tri[0])).cross(p(tri[2]) - p(tri[0]));
            assert!(face.dot(Vec3::from(m.normals[tri[0] as usize])) > 0.0);
        }
    }
}
